version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: atendopro-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-atendopro}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  atendopro-backend:
    image: openjdk:21-jdk
    container_name: atendopro-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET:-MinhaChaveSuperSecretaParaJWT}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-3600000}
    depends_on:
      - postgres

volumes:
  postgres_data:
