# Imagem base do Java 21
FROM maven:3.9.4-eclipse-temurin-21

# Diretório de trabalho dentro do container
WORKDIR /app

# Copiar o pom.xml e baixar dependências
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copiar o código fonte
COPY src ./src

# Compilar o projeto
RUN mvn clean package -DskipTests

# Rodar a aplicação
CMD ["java", "-jar", "target/atendopro-0.0.1-SNAPSHOT.jar"]
